<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Role_List</name>
   <tag></tag>
   <elementGuidId>b24e8c1a-6c1f-4463-9e08-0b396df6d689</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SelectFilterRoles</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SelectFilterRoles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>13063097-426f-4545-b3b7-4373b42361ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>6b8af967-de15-4ec0-b8e4-92d4c57f4f52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SelectFilterRoles</value>
      <webElementGuid>4e8b916a-35d1-44eb-91c0-fc0023d77e41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-valid ng-empty</value>
      <webElementGuid>c277b8ef-9563-43a0-9534-54497afc7b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>vm.filterRoleModel</value>
      <webElementGuid>fbe767ac-691e-48ab-b968-287af3327fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>item as item.RoleName | optionsTrim for item in vm.roles track by item.RoleId</value>
      <webElementGuid>f98b4780-ece0-4c2c-a81f-b925ce4418c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>vm.loadGrades();vm.searchForUser()</value>
      <webElementGuid>cbf212e8-99d6-4ae9-915d-76a6f9ee6b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d1fcf3a-78f7-45b6-bb23-d9cd2ac90c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher</value>
      <webElementGuid>d388c9e4-409c-43c2-8140-563e02b81a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SelectFilterRoles&quot;)</value>
      <webElementGuid>8a8b9690-1499-4ff7-8e15-b29818f3abe8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SelectFilterRoles']</value>
      <webElementGuid>f6c441de-1e22-4210-860c-aec25820ab8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[2]/div[2]/div/select</value>
      <webElementGuid>c1a470a1-7934-4774-aede-9f9456776b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[1]/following::select[2]</value>
      <webElementGuid>ca6ce0b9-00ff-4b5f-93d2-7999bc20e73e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[2]/preceding::select[2]</value>
      <webElementGuid>2d773959-7546-4d49-be90-94bad9f045de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/preceding::select[2]</value>
      <webElementGuid>495f69eb-9a54-4126-bbbb-0a4a13dbc961</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>6345c0df-e752-4e34-8b66-6b995b25cb4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SelectFilterRoles' and @name = 'SelectFilterRoles' and (text() = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher' or . = 'Select RoleTeacherStudentAdminParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2cu admincustom admin 333Admin custom Oparent testSun risesunCo-TeacherMichael_teacher')]</value>
      <webElementGuid>7f238c53-f5d4-4965-aa48-4d162129a13a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
