<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Name_Label</name>
   <tag></tag>
   <elementGuidId>4ce4b542-c1bf-4aa3-a04e-118adca59bfe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lms-truncate.lms-middle.lms-max-width-70.lms-md-max-width-60-imp.lms-max-width-100-imp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8f303b94-5012-4ea5-a695-a2c4b767118c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-truncate lms-middle lms-max-width-70 lms-md-max-width-60-imp lms-max-width-100-imp</value>
      <webElementGuid>a7686ac9-3e08-41ca-892e-0d35a01fbdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2147dce2-f319-4040-b3b8-7c62860ba530</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-max-width-100-imp':usersGrouped[0].IsActive == true}</value>
      <webElementGuid>7246780a-8810-4905-9288-8f0eb594aadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dd dd</value>
      <webElementGuid>84325010-4c6a-4fb8-ae17-4f7ac04423a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;office365Div&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;lms-section&quot;]/div[@class=&quot;lms-container lms-margin-bottom-20&quot;]/div[@class=&quot;row lms-margin-top-20&quot;]/div[@class=&quot;col-xs-12 lms-padding-end-0  lms-org-grid-cont col-md-9&quot;]/div[@class=&quot;lms-clear&quot;]/table[@class=&quot;lms-org-table  smart-form table table-bordered table-striped table-hover lms-reports-tbl lms-reports-manage-table lms-user-managment-tbl lms-table-fixed-layout lms-data-table lms-table-popup ng-table&quot;]/tbody[1]/tr[1]/td[@class=&quot;table-main-xs&quot;]/div[@class=&quot;col-xs-12 col-md-12 lms-padding-end-0&quot;]/div[@class=&quot;lms-truncate lms-inline-block lms-middle lms-line-normal&quot;]/div[@class=&quot;col-xs-12 lms-padding-0&quot;]/a[1]/span[@class=&quot;lms-truncate lms-middle lms-max-width-70 lms-md-max-width-60-imp lms-max-width-100-imp&quot;]</value>
      <webElementGuid>483cc9cd-42c4-4168-9984-a163c4044234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div[3]/div[2]/div[3]/table/tbody/tr/td[2]/div/div/div/a/span</value>
      <webElementGuid>1d3e8adf-be5d-42d1-8f59-9d3b81d00608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='search'])[3]/following::span[1]</value>
      <webElementGuid>18e64612-a9b3-4f29-910e-0b3a73bf59c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Joining Date'])[1]/following::span[2]</value>
      <webElementGuid>5801188a-e1af-48df-8261-4d5d8e719eea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dd@gmail.com'])[1]/preceding::span[2]</value>
      <webElementGuid>09654fc6-4ef3-46f8-8079-aeb6a733070a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit User'])[1]/preceding::span[2]</value>
      <webElementGuid>1dfbf87d-e351-4870-9ff9-12646d7e70fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='dd dd']/parent::*</value>
      <webElementGuid>2155f537-68e5-46a1-93a0-504b07c36767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/div/div/a/span</value>
      <webElementGuid>501b282d-069a-4670-a2c6-439c41ea7c95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'dd dd' or . = 'dd dd')]</value>
      <webElementGuid>c30eaa30-b04a-4960-bc51-89888eb5c780</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
