<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Copy Permissions From_List</name>
   <tag></tag>
   <elementGuidId>bb819461-12ef-4f2c-9958-693bc60b241f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtInheritPermissinFrom']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtInheritPermissinFrom</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ca826dd-f97a-45c5-94f5-984f2644bd87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtInheritPermissinFrom</value>
      <webElementGuid>53809a1e-e40b-42a2-b295-e5676672cfce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>txtInheritPermissinFrom</value>
      <webElementGuid>0f92d9de-8d82-4850-b41d-75552ec01bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lms-select-height ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>c2c1201c-e91e-4302-b2a0-842dd2b0242b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Select Role</value>
      <webElementGuid>a0e213f9-e7db-4d79-a9cd-f05ab15b9f5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Role Teacher  Shadow Teacher   Help Teacher  shadow t  Sun rise </value>
      <webElementGuid>52635a04-9a71-42c3-a6a0-b32d1867ac88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtInheritPermissinFrom&quot;)</value>
      <webElementGuid>f23a3583-8e6b-4295-a792-5165a3a550bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtInheritPermissinFrom']</value>
      <webElementGuid>ba378e95-b7e4-4bed-9062-1069bba753d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(Optional)'])[1]/following::select[1]</value>
      <webElementGuid>9a1e5622-6ed4-400d-af8b-85d57fec7e3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Global Custom Fields'])[1]/preceding::select[1]</value>
      <webElementGuid>cf153200-6b3a-4e64-8dd2-d92a5f2cc918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emergency Number'])[1]/preceding::select[1]</value>
      <webElementGuid>b42f2e16-134e-44f9-9ceb-4a83662e67bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>3bcd21bf-1f6a-4a9e-afd7-4c66d2d0583a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtInheritPermissinFrom' and @title = 'Select Role' and (text() = 'Select Role Teacher  Shadow Teacher   Help Teacher  shadow t  Sun rise ' or . = 'Select Role Teacher  Shadow Teacher   Help Teacher  shadow t  Sun rise ')]</value>
      <webElementGuid>90275b07-c29b-4030-a831-f13bb8e1e82a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
