<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Role Description_TextArea</name>
   <tag></tag>
   <elementGuidId>445292f1-2a26-4c1c-9a1a-7b5ff8d13a8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtRoleDescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtRoleDescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>461bccd9-4b40-4268-b144-1f97e520fa0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27d8fe74-28a9-46b9-8447-193db3c97959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtRoleDescription</value>
      <webElementGuid>20178718-5e70-47b3-92f6-9e330d927778</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>roleDescription</value>
      <webElementGuid>f9cf6c5e-09eb-4658-9744-870814c77df3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>e2d047f9-7b51-4d13-b1fd-69b66b4ffe31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>custom-scroll lms-track-desc-text lms-edges-style-lmtd ng-untouched ng-valid ng-dirty</value>
      <webElementGuid>a56a0b52-3324-48f2-a611-4f84094e5aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Role Description</value>
      <webElementGuid>9e32947f-77f6-4f99-b4ff-479ad49b6f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe what this role can do</value>
      <webElementGuid>ae74e80a-5360-4526-b55b-ecab60bc9187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fc91264b-806a-499b-a39d-3eb80e549eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d74cf581-3555-4794-a537-c09829e2bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wsc-instance</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8c2bdc9f-c340-400e-99b1-36727b415f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtRoleDescription&quot;)</value>
      <webElementGuid>2bc7da07-02b9-4693-a76b-58ac1231ff30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtRoleDescription']</value>
      <webElementGuid>a0de0cc9-4e4d-4daa-a15e-552c10c01fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>328f49c7-6f66-4604-95db-0702f70b3516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'txtRoleDescription' and @title = 'Role Description' and @placeholder = 'Describe what this role can do']</value>
      <webElementGuid>9f608d59-6a0c-4ca6-807b-ef9527984fcd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
