<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub Schools Permissions_CheckBox</name>
   <tag></tag>
   <elementGuidId>d193fe16-fe46-4390-a673-e7d8cc561183</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='lblApplyOnChildSegments']//i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lblApplyOnChildSegments > i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>8b43d669-27ed-4b4e-86e2-40a917c40b30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lblApplyOnChildSegments&quot;)/i[1]</value>
      <webElementGuid>90d8d323-4cf5-4bf5-b19e-c34e7138530d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//label[@id='lblApplyOnChildSegments']/i</value>
      <webElementGuid>b3dcb808-1886-45b5-9b66-6bc82f42e066</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/i</value>
      <webElementGuid>e6c623c9-7423-4fc6-89b4-c8c6363c9451</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
