<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Subject_Button</name>
   <tag></tag>
   <elementGuidId>0b421e5c-138c-4743-ba01-429a204be27a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnAddSubject']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnAddSubject</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>eea255ba-84d2-4c43-a8b6-8f51c9e9f2b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnAddSubject</value>
      <webElementGuid>e076ba00-981d-430c-b6f4-642805dd1ec2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link lms-float-end lms-padding-end-20 lms-add-subject</value>
      <webElementGuid>352d9c48-b841-4a52-b7d2-157fdcfe03e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>tenantEditCntrl.addSubject()</value>
      <webElementGuid>ec9f5f80-0fe0-4fca-adaf-6aac8ceef403</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                         Add subject
                                                    </value>
      <webElementGuid>7d5bb5fe-54b4-44bd-ae3b-fc3d99301492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnAddSubject&quot;)</value>
      <webElementGuid>9ee31212-eb49-4330-a61e-dbc48467b9d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnAddSubject']</value>
      <webElementGuid>48242a31-80e1-46a5-a493-8e8ffc9321e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subjects']/div[2]/div/a</value>
      <webElementGuid>541ca808-75ae-43b3-9775-cc08345a9518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no subject areas added .'])[1]/following::a[1]</value>
      <webElementGuid>586cd1d9-1216-4060-9976-064ab1910791</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[33]/following::a[1]</value>
      <webElementGuid>67713be7-c73b-45f5-8c80-bd210d88f019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate Settings'])[2]/preceding::a[1]</value>
      <webElementGuid>6c4fb04a-9983-4365-8654-1b3dcdb06d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add subject']/parent::*</value>
      <webElementGuid>2b404cde-5a8b-4d8c-9383-cadc1f0ef9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/div[2]/div[2]/div/a</value>
      <webElementGuid>22625cb6-000c-4914-94a0-4ceb7e495e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnAddSubject' and (text() = '
                                                         Add subject
                                                    ' or . = '
                                                         Add subject
                                                    ')]</value>
      <webElementGuid>81f7ef3a-5b3c-4871-a5e1-cd909e719302</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
