<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Done_Button</name>
   <tag></tag>
   <elementGuidId>a78e2b7c-6084-4baa-8122-dc3f43b5c873</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@class=&quot;btn btn-link  lms-solid-border-end&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(13) > td.lms-inline-actions.lms-text-align-end.lms-no-border-start.lms-verical-top > span > button.btn.btn-link.lms-solid-border-end</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>391561a1-5c29-410d-baa1-f0311b70c66b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link  lms-solid-border-end</value>
      <webElementGuid>23336b79-b55c-410a-9a6e-83c44caa01de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>tenantEditCntrl.toggleEditMode(subject,false,true)</value>
      <webElementGuid>7f94554f-63be-4df6-b34a-faf8fb38b74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>tenantEditCntrl.tenantForm['subjectName_' + $index].$invalid || (subject.isInValid &amp;&amp; subject.addTranslation)</value>
      <webElementGuid>b8542a78-38a3-4e11-aabc-75e420d53760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                                                        Done
                                                                    </value>
      <webElementGuid>63c34345-b1e6-4e43-9cb7-5f2d1bd6f5fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;subjects&quot;)/div[@class=&quot;lms-row&quot;]/table[@class=&quot;table table-bordered table-striped table-hover lms-reports-tbl&quot;]/tbody[1]/tr[13]/td[@class=&quot;lms-inline-actions lms-text-align-end lms-no-border-start lms-verical-top&quot;]/span[1]/button[@class=&quot;btn btn-link  lms-solid-border-end&quot;]</value>
      <webElementGuid>9b8de4c8-a3bf-48f6-aa73-578e7297c52e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subjects']/div/table/tbody/tr[13]/td[2]/span/button</value>
      <webElementGuid>67a63325-f00a-4d61-8e79-a0f3b09314f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Translation'])[1]/following::button[1]</value>
      <webElementGuid>7f562620-a175-460c-baac-827ab77ad895</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[33]/following::button[2]</value>
      <webElementGuid>708595b6-fad3-4bf4-9ced-c7e162a4cd7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::button[1]</value>
      <webElementGuid>860bfe92-4686-4c64-841b-52fc18b14405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='There are no subject areas added .'])[1]/preceding::button[2]</value>
      <webElementGuid>d16e0831-b2de-40d2-a6b2-694c356f1fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/table/tbody/tr[13]/td[2]/span/button</value>
      <webElementGuid>919695f6-4cef-4539-8cd9-2389448a6c37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                                                                        Done
                                                                    ' or . = '
                                                                        Done
                                                                    ')]</value>
      <webElementGuid>fbf8f51f-9b20-49ea-bd74-2f34cf64dde9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
