<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit This School_SubTab</name>
   <tag></tag>
   <elementGuidId>cea6e295-78f9-4e11-99fb-6ae7ff8c5237</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnEditTenant</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='btnEditTenantSchool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>92c01d61-fa7c-49fc-b66f-7d2911f35599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-link  lms-text-align-start</value>
      <webElementGuid>57ca4625-d5b8-43e7-a879-821c2aa21339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEditTenant</value>
      <webElementGuid>9bec91e8-f7da-46af-ad7d-78fbe3a087fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.editTenant();</value>
      <webElementGuid>dc7d5f84-4f2a-407b-bd2b-d06c524d98f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Edit institute information</value>
      <webElementGuid>a7862c6e-ae04-47bf-a075-e911a7f4e731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit institute information</value>
      <webElementGuid>c7b78c89-d1fb-402f-b70f-c7aeb4e1add2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnEditTenant&quot;)</value>
      <webElementGuid>2a551013-c8d9-4751-b1f0-8168067c9388</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='btnEditTenant']</value>
      <webElementGuid>5ff8ae20-6113-49b2-a6f9-d0a1772519b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='office365Div']/div/div/div/div/div/div/div[2]/ul/li[2]/a</value>
      <webElementGuid>46da4b9b-f7f9-41e3-b796-48c41a0668fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Edit institute information')]</value>
      <webElementGuid>03e45b06-5da4-438a-948a-3d3e4fa820dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manage Tenant'])[1]/following::a[1]</value>
      <webElementGuid>3c147598-c5ff-46e6-a77c-0e56be115a41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Institute Management'])[1]/following::a[2]</value>
      <webElementGuid>d0b1b2d8-9963-4f4c-8fd3-5d15b18009b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update License'])[1]/preceding::a[1]</value>
      <webElementGuid>5c9271f8-50be-42eb-91e8-10106483bd99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='License Purchased'])[1]/preceding::a[2]</value>
      <webElementGuid>bde46acd-64a3-4880-b354-cba96ff049b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Edit institute information']/parent::*</value>
      <webElementGuid>940f2153-064a-4729-88cb-fa8aef776cd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[2]/a</value>
      <webElementGuid>4e3117ad-728d-4a59-a514-f2dcf2f0b29b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnEditTenant' and @title = 'Edit institute information' and (text() = 'Edit institute information' or . = 'Edit institute information')]</value>
      <webElementGuid>258783d0-f301-4657-aa7a-ff939e6eeec8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
