<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lookups_Tab</name>
   <tag></tag>
   <elementGuidId>de3f858d-c1a6-45be-b3a7-dd3e5f89c77e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//ul[@class=&quot;nav nav-pills nav-stacked&quot;]//li[@heading=&quot;Lookups&quot;]//a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>ul.nav.nav-pills.nav-stacked > li:nth-of-type(8) > a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0887f447-c136-42e1-adb8-69260c369503</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>select()</value>
      <webElementGuid>3c1124a0-7cbe-4d4a-bd62-aa3e37986b7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Lookups</value>
      <webElementGuid>3841cd14-a7da-4652-991f-22477b7048ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divAddEditTenantTemplate&quot;)/form[@class=&quot;smart-form  lms-container  lms-xs-no-padding-start lms-xs-no-padding-end  lms-padding-top-20  ng-pristine ng-valid-maxlength ng-valid ng-valid-required ng-valid-minlength ng-valid-pattern ng-valid-min ng-valid-max&quot;]/fieldset[@class=&quot;lms-margin-bottom-20 lms-padding-0&quot;]/div[@class=&quot;lms-padding-bottom-20&quot;]/div[@class=&quot;tabs-pills custom-scroll&quot;]/div[@class=&quot;lms-admin-tabs&quot;]/ul[@class=&quot;nav nav-pills nav-stacked&quot;]/li[8]/a[1]</value>
      <webElementGuid>6bf4c096-0645-48de-91ea-7533e94203f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditTenantTemplate']/form/fieldset/div/div/div/ul/li[8]/a</value>
      <webElementGuid>862cd8f8-286b-4fa8-8c6a-e2ddff0f2d76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Lookups')]</value>
      <webElementGuid>16d2162c-4f57-485a-b94d-b596ada2986c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gamification Settings'])[1]/following::a[1]</value>
      <webElementGuid>0edf7a14-ee61-4d33-a330-1df02e295333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learning Objectives'])[1]/following::a[2]</value>
      <webElementGuid>6fe3358f-91b4-48f3-8cf0-39872095944c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Permissions'])[1]/preceding::a[1]</value>
      <webElementGuid>099c20f2-6547-4c1c-9ad5-b939f413a928</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Certificate Settings'])[1]/preceding::a[2]</value>
      <webElementGuid>25053739-1e85-48ac-b955-7336ab6a07e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lookups']/parent::*</value>
      <webElementGuid>4131bd9f-44d4-4d34-9b28-a9a932f3bd83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[80]</value>
      <webElementGuid>6563b576-0f1f-4f7b-8a43-2b1a64fba786</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/div/ul/li[8]/a</value>
      <webElementGuid>4c20f818-aea2-465d-905f-797c9e903626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Lookups' or . = 'Lookups')]</value>
      <webElementGuid>16d769a6-71bf-406a-8472-19fc30b07e86</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
