<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Subjects_Button</name>
   <tag></tag>
   <elementGuidId>0593da58-1be8-429b-b41b-501ab813880c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnSaveTenantInfo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnSaveSchool']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>23d50b57-a788-455c-8059-3ef16138e67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnSaveTenantInfo</value>
      <webElementGuid>50b9b71d-fecc-42f8-bf0f-c623c7820084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>13487aba-1f95-497a-a40c-986f73f4eddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>tenantEditCntrl.save()</value>
      <webElementGuid>ce8f18e7-baf0-409e-a4fe-88da3a50393b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>tenantEditCntrl.AddEditModePublic || tenantEditCntrl.isBusy ||tenantEditCntrl.isSaveButtonBusy</value>
      <webElementGuid>b6d5bc8d-3cc1-45dc-84ec-2b178f6a0466</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>beb27ee2-05bd-43ba-a974-b0d233d971b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnSaveTenantInfo&quot;)</value>
      <webElementGuid>04a76c75-2048-4c94-9730-a8e4d9370ae3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnSaveTenantInfo']</value>
      <webElementGuid>88002a0e-9f3a-47b6-9522-b1fe700ccd26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditTenantTemplate']/form/footer/button[2]</value>
      <webElementGuid>05fe76f8-a6e0-48b6-a9de-9eb24253f0b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/following::button[1]</value>
      <webElementGuid>5e032dc5-328d-426b-98f5-5513a8b54c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recent Chats'])[1]/preceding::button[1]</value>
      <webElementGuid>92e51580-efe7-4af5-bd7f-af6d203c8f6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Login'])[1]/preceding::button[1]</value>
      <webElementGuid>1af192b6-bcf6-4de7-bc80-caaf16363721</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>052c6b4c-3a7c-4dee-8030-adb22ee53ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/button[2]</value>
      <webElementGuid>cfa6163c-cb4b-45bc-9a8e-adb91f896ec9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnSaveTenantInfo' and (text() = ' Save' or . = ' Save')]</value>
      <webElementGuid>d4dc2434-825e-4d00-88c5-f286e42f2006</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
