<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Subject Name_TextField</name>
   <tag></tag>
   <elementGuidId>704e8dde-55a7-4e42-83eb-d116079c3724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtsubjectName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtsubjectName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b5c8590-abd5-4eb7-9369-ed5ac9ed2a1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtsubjectName</value>
      <webElementGuid>97af2b65-56c3-4d01-b2fd-2c3ed9d29021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4737d8ab-0d5e-4927-8764-9fe065110bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>subjectName_12</value>
      <webElementGuid>30aa3db9-36ad-40aa-a30e-df46c7155bb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>60e2853b-2b3e-4c68-8b1e-6318608606ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>199</value>
      <webElementGuid>a8841027-258e-4a6f-8dac-c8e979871ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lms-width-65 lms-xs-width-100 ng-untouched ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse ng-valid ng-valid-required success</value>
      <webElementGuid>0286934c-2962-4208-b060-5c65f79a2e60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>English</value>
      <webElementGuid>46baafb5-4d8a-45c0-9fdf-22e74b94b5d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>subject.Name</value>
      <webElementGuid>003623bb-5c14-4e76-ab9e-f6bff9f5476b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>subject.editMode &amp;&amp; !subject.addTranslation</value>
      <webElementGuid>6edeaea7-14d3-4054-80e7-56326bc082ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error':tenantEditCntrl.tenantForm['subjectName_' + $index].$invalid &amp;&amp; tenantEditCntrl.tenantForm['subjectName_' + $index].$error.required  &amp;&amp; (!tenantEditCntrl.tenantForm['subjectName_' + $index].$pristine || tenantEditCntrl.submitted)
                                                                || tenantEditCntrl.tenantForm['subjectName_' + $index].$invalid &amp;&amp; tenantEditCntrl.tenantForm['subjectName_' + $index].$error.maxlength  &amp;&amp; (!tenantEditCntrl.tenantForm['subjectName_' + $index].$pristine || tenantEditCntrl.submitted)
                                                                ,'success':tenantEditCntrl.tenantForm['subjectName_' + $index].$valid &amp;&amp; !tenantEditCntrl.tenantForm['subjectName_' + $index].$pristine}</value>
      <webElementGuid>bbe1dbfb-c05a-4624-8f94-8f0ce9034526</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21c3d5e6-5d0b-43db-9938-2f97cd41fdb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtsubjectName&quot;)</value>
      <webElementGuid>e14cb465-eb00-43cb-8aeb-c10343c8ad48</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtsubjectName']</value>
      <webElementGuid>c17d6685-6e06-4a29-a000-a042efed521d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='subjects']/div/table/tbody/tr[13]/td/input</value>
      <webElementGuid>8b9b88cb-f15f-42fc-a387-87b62f3a680b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/input</value>
      <webElementGuid>493b56b2-4cc2-42a0-8444-59ddf163fe92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'txtsubjectName' and @type = 'text' and @name = 'subjectName_12' and @title = 'English']</value>
      <webElementGuid>e55d2c8f-c782-4ce4-921f-6528b392f5b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
