<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cancel_Button</name>
   <tag></tag>
   <elementGuidId>630b003e-a87b-4e65-92ae-57c0d7e55506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.col-xs-12.lms-text-align-end.lms-padding-0 > #btnCancelProvisionUsers</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@class='btn btn-default lms-height-unset  lms-edit-mode-btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d23bab30-0a5f-4748-a976-27d8fe1766bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default lms-height-unset  lms-edit-mode-btn</value>
      <webElementGuid>56184a9c-e96a-4ed9-9f6f-e699dfa7c39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnCancelProvisionUsers</value>
      <webElementGuid>7b61d382-5d80-4bab-b295-06b3996db01e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cdfd5be7-371c-4f8d-a2cb-29c8b8e7cb5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.cancelNewUser()</value>
      <webElementGuid>008e6e11-f844-4b52-a5c3-c270c73d8590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-edit-mode-btn':AddEditUserCtrl.isInEditMode}</value>
      <webElementGuid>8e55e0cc-6371-45eb-8637-40bc6709090c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Cancel
            </value>
      <webElementGuid>2a92d2d7-4b0e-4316-b5ee-378e1c47b8a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;font-s--1 lms-font-montserrat-regular js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage no-websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths web-font&quot;]/body[@class=&quot;minified smart-ltr desktop-detected scrolled shrinked-header modal-open&quot;]/div[@class=&quot;modal fade in&quot;]/div[@class=&quot;modal-dialog modal-lg&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;lms-row lms-clear&quot;]/footer[@class=&quot;lms-row lms-clear lms-margin-top-20 modal-footer&quot;]/div[@class=&quot;col-xs-12  lms-text-align-end  lms-padding-0&quot;]/button[@id=&quot;btnCancelProvisionUsers&quot;]</value>
      <webElementGuid>6c45bf39-2760-4d17-a25a-85517e28fe6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@id='btnCancelProvisionUsers'])[2]</value>
      <webElementGuid>c1d15937-1cf9-481f-8a7c-0ad74f60e3d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[2]/following::button[1]</value>
      <webElementGuid>18d4a780-35b2-430e-8833-f40ef6f2160c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::button[2]</value>
      <webElementGuid>8d3f343b-242c-4456-bc65-1fc1cb3f67e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button[2]</value>
      <webElementGuid>850cb10a-7e37-4be8-bccd-bcf71210ddfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnCancelProvisionUsers' and @type = 'button' and (text() = '
                Cancel
            ' or . = '
                Cancel
            ')]</value>
      <webElementGuid>ce4cab71-4f74-4322-bebe-f5af9737b695</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
