<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Edit User_Button</name>
   <tag></tag>
   <elementGuidId>ea7a63c6-7d11-44ba-8928-332819e60704</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.dropdown.btn-group.lms-padding-0.lms-float-end.open > ul.dropdown-menu.pull-right.lms-menu-content > li > #btnEditUser</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='dropdown btn-group lms-padding-0 lms-float-end open']//a[@id='btnEditUser']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a38d5757-f20a-4b23-bc8d-139994abd962</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnEditUser</value>
      <webElementGuid>d3056d31-10c0-4187-a6a7-f077256adc2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.launchAddEditUserPopUp(usersGrouped,vm.tenantSchools)</value>
      <webElementGuid>5003fbd4-45d9-40b0-8e5c-840bcdf9a0be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>e5abf8f9-32f3-4ef9-859f-6f4c43abd887</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-if</name>
      <type>Main</type>
      <value>!vm.isLearningCurve</value>
      <webElementGuid>8f299436-1bff-456a-8c9b-f8e58c4f1b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Edit User</value>
      <webElementGuid>efc5c11b-45d9-48c9-9294-4d4fb575a847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;office365Div&quot;)/div[1]/div[1]/div[1]/div[@class=&quot;lms-section&quot;]/div[@class=&quot;lms-container lms-margin-bottom-20&quot;]/div[@class=&quot;row lms-margin-top-20&quot;]/div[@class=&quot;col-xs-12 lms-padding-end-0  lms-org-grid-cont col-md-9&quot;]/div[@class=&quot;lms-clear&quot;]/table[@class=&quot;lms-org-table  smart-form table table-bordered table-striped table-hover lms-reports-tbl lms-reports-manage-table lms-user-managment-tbl lms-table-fixed-layout lms-data-table lms-table-popup ng-table&quot;]/tbody[1]/tr[1]/td[@id=&quot;liTrackList_0&quot;]/div[@class=&quot;col-xs-12&quot;]/div[@class=&quot;dropdown btn-group lms-padding-0 lms-float-end open&quot;]/ul[@class=&quot;dropdown-menu pull-right lms-menu-content&quot;]/li[1]/a[@id=&quot;btnEditUser&quot;]</value>
      <webElementGuid>9714cdc7-5109-46e5-8290-47ee4b51f70c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@id='btnEditUser'])[2]</value>
      <webElementGuid>b6ddfa6e-66ee-46e6-b8ad-cdf5f7afb0e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//td[@id='liTrackList_0']/div/div/ul/li/a)[5]</value>
      <webElementGuid>e77b7401-1502-4a19-9a60-987a94003f88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Edit User')])[2]</value>
      <webElementGuid>41dfc9ba-20eb-4f08-a050-12bc4fcb43e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Parent School'])[2]/following::a[2]</value>
      <webElementGuid>163afb0a-eb31-418c-84e0-0b1a555430b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teacher'])[4]/following::a[2]</value>
      <webElementGuid>3e67a544-a328-4f67-8ee6-2d3df5afa75b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Activate User'])[2]/preceding::a[1]</value>
      <webElementGuid>98f7edec-9572-4b21-9e80-abb950c08ad4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deactivate User'])[2]/preceding::a[2]</value>
      <webElementGuid>b512a97d-18ab-4a01-b992-6a388361d9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[17]</value>
      <webElementGuid>b1ed9d70-f961-4c11-8d22-c17af3055c8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[10]/div/div/ul/li/a</value>
      <webElementGuid>0d170acd-8bd2-4f8d-b6b6-d68409ae155f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'btnEditUser' and @href = 'javascript:void(0);' and (text() = 'Edit User' or . = 'Edit User')]</value>
      <webElementGuid>651a242d-2a42-4075-9988-fe3a8e8da6ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
