<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Mathematics_Option</name>
   <tag></tag>
   <elementGuidId>e3028f5d-2598-4342-9dc9-1d222899a279</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(9) > a.item-unselected.truncate-full-width.display-block</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@title='Mathematics']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3be10ae0-499b-4548-87a5-8a63becb2b48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-unselected truncate-full-width display-block</value>
      <webElementGuid>d8354492-b1e8-4903-a410-2bb2f2ac804c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>9cf58815-c6a9-40a5-b331-944303dd830a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mathematics</value>
      <webElementGuid>683785b4-5fe9-421b-ab19-c4cc93165ccf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-click</name>
      <type>Main</type>
      <value>toggleItem(option); $event.stopPropagation()</value>
      <webElementGuid>d01debea-35f0-494f-8f7d-cf864dd0feda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Mathematics
            </value>
      <webElementGuid>4e2bd294-35c5-48be-8126-a408dec894b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;multiSubjects&quot;)/div[@class=&quot;btn-group&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-form lms-edges-style-lmtd&quot;]/li[9]/a[@class=&quot;item-unselected truncate-full-width display-block&quot;]</value>
      <webElementGuid>ff61103c-81aa-4585-bf49-41647549837e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//custom-multiselect[@id='multiSubjects']/div/ul/li[9]/a</value>
      <webElementGuid>1689dd24-8476-4072-a308-c5f020361e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Mathematics')]</value>
      <webElementGuid>eaa27e52-1edf-4594-a127-4da0824b8697</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language Arts'])[1]/following::a[1]</value>
      <webElementGuid>499bf0bb-2b08-4c73-a894-7c35ee397f3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Creative Arts'])[2]/following::a[2]</value>
      <webElementGuid>e70bfa21-b4a6-4b4c-8bad-70c2fde2923c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Others'])[1]/preceding::a[1]</value>
      <webElementGuid>91f9d240-6de9-4868-98a5-0a803d14a1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Physical Education &amp; Health'])[1]/preceding::a[2]</value>
      <webElementGuid>83be8b94-ca73-4849-9350-571b1cf4de75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mathematics']/parent::*</value>
      <webElementGuid>aadaad96-5197-4177-a094-c00f14b23553</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '')])[186]</value>
      <webElementGuid>eda3b25e-e809-46ba-be79-1ad91c91726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//custom-multiselect/div/ul/li[9]/a</value>
      <webElementGuid>e6cf5a5d-7c85-43ba-bda1-5ca986b38539</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Mathematics' and (text() = '
                Mathematics
            ' or . = '
                Mathematics
            ')]</value>
      <webElementGuid>315d28c8-f69c-4eb3-a32c-3a13a7d8b86f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
