<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Popup Ok_Button</name>
   <tag></tag>
   <elementGuidId>64de7e14-47c4-4856-aa03-ee7ab8fe0078</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDialogOk</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDialogOk']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c91fb0fe-00ed-4dec-9981-a60eef615654</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDialogOk</value>
      <webElementGuid>b871c146-fa88-4edf-8855-9642ea16a581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary lms-qb-btn-primary </value>
      <webElementGuid>991c7f12-645b-4ff2-9769-3a54c7c3c5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>dialogCntrl.ok()</value>
      <webElementGuid>c6339d2e-c614-4f95-90a0-3e437c710cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Ok
        </value>
      <webElementGuid>f29df41b-bae8-45e7-8467-c507bbe4c9f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDialogOk&quot;)</value>
      <webElementGuid>bf28021e-9fce-4c69-9af3-1218393a2a78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDialogOk']</value>
      <webElementGuid>603c5ef3-5d2e-4f6e-87b6-592dcfd66472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Confirm'])[1]/following::button[1]</value>
      <webElementGuid>22c57c7c-8acf-4bda-888f-ef98ecdba6a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[2]/following::button[1]</value>
      <webElementGuid>16a6f8f4-01c5-4d37-b96f-42fbdf7e727e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::button[1]</value>
      <webElementGuid>cd62b7ec-a783-426b-8422-4a61e5d425d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ok']/parent::*</value>
      <webElementGuid>598ace1b-8ce8-4b91-8156-34dfb5a6c6aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/footer/button</value>
      <webElementGuid>715d8bea-6f59-485f-af66-bc6f81c035a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnDialogOk' and (text() = '
            Ok
        ' or . = '
            Ok
        ')]</value>
      <webElementGuid>395d4258-29cf-4e76-8af7-e05b2d315a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
