<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Roles_List</name>
   <tag></tag>
   <elementGuidId>2af08879-021b-4403-9c19-062912d839aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'txtUserRole1' and @name = 'Role[$index]' and (text() = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2Admin custom Oparent testSun risesunCo-TeacherMichael_teacher' or . = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2Admin custom Oparent testSun risesunCo-TeacherMichael_teacher')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtUserRole1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@class=&quot;input  lms-padding-end-0&quot;]//select[@id=&quot;txtUserRole1&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1a2b0fef-0967-4c2d-9839-c9054bb8328f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>dafeb7bc-97ba-4a30-b71d-49ea61aee784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>43b572c4-109c-4b43-8825-8f4064f36cd7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtUserRole1</value>
      <webElementGuid>c4f892cf-01ec-4787-bf41-25ba991af6f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Role[$index]</value>
      <webElementGuid>84bdb9bd-ced1-4da3-b9d1-819c4978673e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>userRole.SelectedRoleId</value>
      <webElementGuid>47955820-fac2-44d2-a985-bb99a58f4cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-change</name>
      <type>Main</type>
      <value>AddEditUserCtrl.EdRoleChanged(userRole.SelectedRoleId,$index)</value>
      <webElementGuid>9ad78718-73c0-4c70-b38c-7f5045297b0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>1675ec41-e3e6-4548-b313-d1d4681536c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.RoleId as option.RoleName | optionsTrim:'20':'25':'40' | translate for option in userRole.EDModeRoles</value>
      <webElementGuid>c5fe0520-f5e0-4838-ac7a-2d7b35e5a22f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.Role[$index].$invalid &amp;&amp; AddEditUserCtrl.userForm.Role[$index].$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Role[$index].$pristine)}</value>
      <webElementGuid>76ccf685-aedd-4b3f-b7a7-8a4e729a8255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c3cc8bbe-9255-4154-ade4-121432d581b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2Admin custom Oparent testSun risesunCo-TeacherMichael_teacher</value>
      <webElementGuid>41ce0dd5-ee03-42e0-8e3d-d44b20c989b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtUserRole1&quot;)</value>
      <webElementGuid>ef7d2599-3ed7-4e5a-80b0-72623e4fed45</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtUserRole1']</value>
      <webElementGuid>77f06c3b-15c1-40ca-ac48-31dd216b8b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liUserMultiRoles1']/div/div/div/div[2]/div/select</value>
      <webElementGuid>27133c4d-a74b-4956-83fc-e839ce09a0e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Role'])[2]/following::select[1]</value>
      <webElementGuid>7343043e-87d5-488f-b077-2cf90ed9d1b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='esraa subschool'])[2]/following::select[1]</value>
      <webElementGuid>45ff0450-2b17-44a1-9342-a399e144576f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::select[1]</value>
      <webElementGuid>b61ac766-cbee-470c-ad6d-01aa5a5cd699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::select[1]</value>
      <webElementGuid>f67570cc-b9c5-4947-ac9a-21653b177a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/div/div/div/div[2]/div/select</value>
      <webElementGuid>f911d161-9a1c-49a7-b18b-5a77bedcd9a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'txtUserRole1' and @name = 'Role[$index]' and (text() = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2Admin custom Oparent testSun risesunCo-TeacherMichael_teacher' or . = ' RoleTeacherStudentParentAcademic CoordinatorShadow TeacherHelp Teacherco adminGuest Studentacac newshadow tstudent 2Admin custom Oparent testSun risesunCo-TeacherMichael_teacher')]</value>
      <webElementGuid>9b55db43-fd7c-4ab0-9756-7ade73669ddb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
