<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save Role_button</name>
   <tag></tag>
   <elementGuidId>89fd52ad-c566-4f88-893f-e230e062e7fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnDoneUserRole</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnDoneUserRole']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a5af3c0c-a189-49b9-8d4d-2127d0bca791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>840327b7-6045-448a-9a28-4970dbc9b97b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnDoneUserRole</value>
      <webElementGuid>627518e8-7212-4640-808a-42eb90f101db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn text-muted  btn-link lms-solid-border-end lms-xs-padding-start-0 lms-xs-only-text-start color-lnks</value>
      <webElementGuid>ca405766-c0bf-4e60-b96a-1287ab4f3767</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value> Save</value>
      <webElementGuid>62cd56e4-472e-4415-81d4-4013015e9792</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.doneNewUserRole($index)</value>
      <webElementGuid>b5ff41e6-31e4-4cab-8cb4-3aec5fded2a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>userRole.SelectedRoleId == undefined ||  userRole.SelectedRoleId == null || !AddEditUserCtrl.isAvailableRole(userRole.SelectedRoleId) || userRole.roleError || !AddEditUserCtrl.userForm.$valid</value>
      <webElementGuid>ecbafb9f-b0e0-4078-9f06-1a4b41f942dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'color-lnks': !(userRole.SelectedRoleId == undefined ||  userRole.SelectedRoleId == null || userRole.roleError || !AddEditUserCtrl.userForm.$valid)}</value>
      <webElementGuid>f4fb1a63-e25e-43d8-82ba-bcac952ad7c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                             Save
                                        </value>
      <webElementGuid>8d7ca49c-db63-4521-b3c0-51bf358ef67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnDoneUserRole&quot;)</value>
      <webElementGuid>fa05e1f0-4c99-4f18-b92f-d620512d61cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnDoneUserRole']</value>
      <webElementGuid>925015b4-b6ee-45c9-b868-e4901c491f37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liUserMultiRoles1']/div/div/div[3]/button</value>
      <webElementGuid>c41377aa-1e03-44e7-a417-b87d3815589a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='zzzzzzzzzzzz'])[1]/following::button[1]</value>
      <webElementGuid>ef015cf9-221c-4f43-96cf-da133ab8c926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='World Languages'])[1]/following::button[1]</value>
      <webElementGuid>35e5b8f5-4e3e-4e48-8b04-91a27ab1b32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>0e49ffb8-0164-4421-8f40-60e24be4bce2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/preceding::button[2]</value>
      <webElementGuid>5db6843c-0dd8-4bfc-be26-1d47dc649e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>facad8be-fed2-4b21-b791-15bfa655fe6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>5329fc4a-1ea7-4f2d-b0ce-4d2141a4014b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btnDoneUserRole' and @title = ' Save' and (text() = '
                                             Save
                                        ' or . = '
                                             Save
                                        ')]</value>
      <webElementGuid>b9a39a57-cc58-4d61-afb0-0f58b828b1ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
