<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Email_Label</name>
   <tag></tag>
   <elementGuidId>b5e8ae82-d5dd-4ea8-901b-8b40039ee98e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.truncate.lms-min-width-230.lms-text-align-start</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@class='truncate lms-min-width-230 lms-text-align-start']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>103d55ce-f016-45b2-8c16-1cc24189ea6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>truncate lms-min-width-230 lms-text-align-start</value>
      <webElementGuid>fdde36dd-7422-46a7-9222-7eb6bdec8e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>2d18d516-e2f8-412a-b154-61a8d9d1c702</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>dd@gmail.com</value>
      <webElementGuid>975055a1-d57e-498c-a2a5-6c9476406c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divAddEditUser&quot;)/div[1]/div[1]/form[@class=&quot;smart-form ng-pristine ng-valid ng-valid-max-tags ng-valid-min-tags ng-valid-leftover-text&quot;]/div[@class=&quot;lms-fields-cont custom-scroll lms-padding-20&quot;]/fieldset[1]/div[@class=&quot;lms-row lms-clear lms-main-sec&quot;]/div[@class=&quot;lms-row lms-clear&quot;]/div[@class=&quot;col-xs-8  lms-font-size-14imp&quot;]/div[@class=&quot;col-xs-12 col-sm-8 col-md-8 col-lg-8 lms-padding-end-0 lms-padding-start-15-imp lms-margin-start-20&quot;]/div[@class=&quot;lms-row lms-clear lms-margin-top-10-imp&quot;]/div[@class=&quot;col-md-6 lms-padding-start-0 lms-flex lms-flex-wrap-none&quot;]/span[@class=&quot;truncate lms-min-width-230 lms-text-align-start&quot;]</value>
      <webElementGuid>f58c7a63-7f94-4575-b9a3-df1dac1bfb69</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div/div[2]/div[2]/div/span</value>
      <webElementGuid>468137d4-e64c-459a-8cc6-1db99273bdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='dd dd'])[2]/following::span[1]</value>
      <webElementGuid>42274a55-7ccb-4a3e-92af-b78b967f425a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::span[1]</value>
      <webElementGuid>8597faf2-ec51-4b46-a6f0-acf4ede8d1ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='list:'])[1]/preceding::span[1]</value>
      <webElementGuid>e4c5faf0-8a1d-4450-b5d8-867adbe6006e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span</value>
      <webElementGuid>5a49f857-d9bb-4e0d-b885-aab4f7775c8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'dd@gmail.com' or . = 'dd@gmail.com')]</value>
      <webElementGuid>c16917c1-11ad-41f7-ab24-5288c7214e30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
