<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Show Password_Icon</name>
   <tag></tag>
   <elementGuidId>815211b7-95b9-441e-b12e-34e8d0b2bb16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnShowPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em.fa.fa-eye-slash.lms-font-base-imp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>a9f74bcd-89e2-4246-94fd-19dc10e4eb39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-eye-slash lms-font-base-imp</value>
      <webElementGuid>585b1a04-3ae8-4e5b-80a7-2bc4d0ec2661</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnShowPassword&quot;)/em[@class=&quot;fa fa-eye-slash lms-font-base-imp&quot;]</value>
      <webElementGuid>a62c207a-8a66-4303-baa5-f276e91400eb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btnShowPassword']/em</value>
      <webElementGuid>9798ba0f-6ace-4024-8987-92c9d3336ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/button/em</value>
      <webElementGuid>a332ec02-5df2-4990-9946-76ca9856ebec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
