<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Emergency Number_TextField</name>
   <tag></tag>
   <elementGuidId>83750362-d8cf-4b9e-98dd-76d69178271d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtCustomField0']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCustomField0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2de8eae1-451e-45b3-acda-b0d18c2236f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>f47c449f-0f45-4153-85da-62aad012b963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCustomField0</value>
      <webElementGuid>30070a37-5536-4b13-b7ee-0eb770ba49b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCustomField0</value>
      <webElementGuid>e84afe3e-4771-47bb-bed6-b6622d4298b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-disabled':customFieldListCtrl.disabled , 'border-error': ( customFieldListCtrl.customFieldForm.txtCustomField0.$invalid &amp;&amp; !customFieldListCtrl.customFieldForm.txtCustomField0.$pristine) || (customFieldListCtrl.customFieldForm.txtCustomField0.$invalid &amp;&amp; submitted )   , 'success': customFieldListCtrl.customFieldForm.txtCustomField0.$valid &amp;&amp; customFieldListCtrl.customFieldForm.txtCustomField0.$touched }</value>
      <webElementGuid>26d4780e-2538-4bfb-aa3e-7007537066bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control lms-width-100-imp ng-untouched ng-valid ng-valid-min ng-valid-max ng-valid-required ng-valid-minlength ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>019bba1d-0ea3-4477-94ff-6f96090c2078</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>customField.NumberValue</value>
      <webElementGuid>7cf05347-5641-47da-abf5-09b067b1b390</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b7f01d4d-bfc7-4cfc-956b-5b2ba6f8ca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>max</name>
      <type>Main</type>
      <value>2147483647</value>
      <webElementGuid>2e67fe1f-f808-4c4f-8bf6-b023714816fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>40942114-56ad-4e50-87bd-219b97975790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>customField.IsRequired</value>
      <webElementGuid>304df0b7-ab9a-4ccd-be2e-6a6ebb2a26b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>1d185c74-30cc-4405-981d-28419b3dacae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fadd8187-41ec-4ca4-85c5-a8e9572f37d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCustomField0&quot;)</value>
      <webElementGuid>35547fa0-f130-4880-95cf-eba1d4e39e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtCustomField0']</value>
      <webElementGuid>5ac96195-90c1-4894-a641-10ab78ad204c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div[3]/div/div/div/div/div/custom-field-list/div/div/ng-form/div/div/input</value>
      <webElementGuid>d7df717a-411d-4008-99ea-e6e06d335716</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ng-form/div/div/input</value>
      <webElementGuid>49c0389a-fe9a-4a4a-81ab-d1b86d003173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @id = 'txtCustomField0' and @name = 'txtCustomField0']</value>
      <webElementGuid>c4be8d2c-83ba-4e21-9d87-c4061b341c93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
