<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>L2_Option</name>
   <tag></tag>
   <elementGuidId>468f8e25-0e0b-4c35-a497-23bb25959ebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[normalize-space()='L2']//i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-of-type(5) > a > label.checkbox.lms-truncate.lms-margin-top-0.lms-padding-start-15 > i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>38a0f948-b045-4bb8-8d60-5f975d778056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCustomField2&quot;)/div[@class=&quot;multiselect-parent btn-group dropdown-multiselect lms-full-width&quot;]/ul[@class=&quot;dropdown-menu dropdown-menu-form  custom-scroll lms-custom-field-menu lms-full-width&quot;]/li[5]/a[1]/label[@class=&quot;checkbox lms-truncate lms-margin-top-0 lms-padding-start-15&quot;]/i[1]</value>
      <webElementGuid>36849192-a3a2-42ae-b3cd-e00f7fb80d38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='txtCustomField2']/div/ul/li[5]/a/label/i</value>
      <webElementGuid>114d6d6b-3602-458d-9265-9fe72271b27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[5]/a/label/i</value>
      <webElementGuid>fcfe5489-383d-48ee-96ee-59062cdc0069</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
