<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Languages_List</name>
   <tag></tag>
   <elementGuidId>0a8a8b82-d07f-46c3-a77a-bd6c981442a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='txtLanguage']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtLanguage</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ea85449f-aed4-4d8f-9147-80cbe5f2678f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>listview</value>
      <webElementGuid>f9ae7f56-dbba-4ba0-bb3c-99aac6c6e814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>c8414019-0316-42c0-a44e-67a37f6b7314</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>cbdf9d71-ae62-4759-bbfd-07a80502d114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Language</value>
      <webElementGuid>d564086d-6551-45a3-85ca-7f32dd473ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtLanguage</value>
      <webElementGuid>deebbecd-d7ad-4818-b4e6-38c2b74c10a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.Language</value>
      <webElementGuid>4ddf3c7f-1096-4b13-bbac-9337ae37a014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-options</name>
      <type>Main</type>
      <value>option.UrlPath as option.DisplayName for option in AddEditUserCtrl.availableLanguages</value>
      <webElementGuid>4c5ff911-b391-4d13-8bfe-d7faed6cc859</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error':AddEditUserCtrl.userForm.Language.$invalid &amp;&amp; AddEditUserCtrl.userForm.Language.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Language.$pristine || submitted)}</value>
      <webElementGuid>1a6ed3ee-e3a0-43b0-a863-28c651b8e34b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>04dfb5e9-181f-413d-a3f9-f46522989306</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LanguageEnglishالعربيةEspañolFrançaisPortuguês</value>
      <webElementGuid>d53dc79a-8038-48ed-9a86-bb33c6e3222b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtLanguage&quot;)</value>
      <webElementGuid>0a8e383d-9195-4830-9556-e56630842cf0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='txtLanguage']</value>
      <webElementGuid>115d747b-e518-45e6-b592-e32226785386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div/div/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>0b605588-746d-48ff-911f-eaa69c814591</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::select[1]</value>
      <webElementGuid>b89cbcdf-28ce-4629-889c-af247ae9c8eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/preceding::select[1]</value>
      <webElementGuid>b7c54c76-e9bc-4d6b-801b-23cf9389fea6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/select</value>
      <webElementGuid>d38dcd2b-e8c8-49e1-9774-7d737a0fd321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'Language' and @id = 'txtLanguage' and (text() = 'LanguageEnglishالعربيةEspañolFrançaisPortuguês' or . = 'LanguageEnglishالعربيةEspañolFrançaisPortuguês')]</value>
      <webElementGuid>d02a052b-239b-4308-862b-8ade6d399fab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
