<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Parent School_Button</name>
   <tag></tag>
   <elementGuidId>a3b32012-4a02-4185-a3e4-fa58b76eb7cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9d1ec7e-95a7-4991-aa28-b1bf17cb00b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>auto</value>
      <webElementGuid>5e82e440-772e-413b-b84d-c6e659df7fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>school_94ba5777-f176-43d7-844d-229f9789ba53</value>
      <webElementGuid>1f12e75a-a43e-4951-986f-902d4b142600</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>vm.selectSchoolNode(node,$event)</value>
      <webElementGuid>7548f10d-2ac0-4b52-9f50-a9dd7f36f2f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-tree-selected': node.SchoolId == vm.currentSelectedSchool.SchoolId}</value>
      <webElementGuid>55f7fc50-dd10-4001-8b1b-d04e0ba8a8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-tree-name</value>
      <webElementGuid>5131c965-4327-4424-b16d-3644301f46d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Parent School</value>
      <webElementGuid>d85f3135-fb34-4aca-a770-806154b7f358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b32920de-e4d0-4163-9e24-e47ce0711ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e3cd128f-c219-45c3-9337-1af7aa7b1fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
            Parent School
        </value>
      <webElementGuid>cb2f4702-4da3-4708-8313-c2abbb718231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;school_94ba5777-f176-43d7-844d-229f9789ba53&quot;)</value>
      <webElementGuid>c73af59b-6e89-4306-a2cd-95e412ce89f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='school_94ba5777-f176-43d7-844d-229f9789ba53']</value>
      <webElementGuid>141e4a86-1701-400a-b757-5833c455b2c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='liEle0']/div/span</value>
      <webElementGuid>acef26ca-1f3c-4b27-b023-5c8e421968cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Organization'])[3]/following::span[2]</value>
      <webElementGuid>d2a4a679-6fb7-4442-8130-b2fe5699bc8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include people in schools and sub schools'])[1]/following::span[3]</value>
      <webElementGuid>169ef761-95c2-49d6-bf86-9ced1f4e79b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Primary School'])[3]/preceding::span[1]</value>
      <webElementGuid>e6b6ae88-e7ad-431e-96ea-af953bee0412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Second school'])[1]/preceding::span[7]</value>
      <webElementGuid>f67ebef0-dcaa-4358-aa81-a5f280c97fef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Parent School']/parent::*</value>
      <webElementGuid>122eae36-8192-4a24-ab2c-f9745c34b5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ol/li/div/span</value>
      <webElementGuid>0d65f9ca-95c6-4f99-b0d6-86e03dd2b62a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'school_94ba5777-f176-43d7-844d-229f9789ba53' and @title = 'Parent School' and (text() = '
            Parent School
        ' or . = '
            Parent School
        ')]</value>
      <webElementGuid>20eb4724-a1ee-432d-97e9-56c1d1aeb64b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
