<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Save_Button</name>
   <tag></tag>
   <elementGuidId>fb629da3-0876-41ad-9fef-961000fde083</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnClosePopup']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btnClosePopup</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>72fb30a3-9c02-414a-aeaf-33eb613bff5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-transparent-bg lms-border-none lms-padding-end-5 lms-outline-0 text-muted</value>
      <webElementGuid>1081d013-392a-4edd-a472-34641b1f0f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnClosePopup</value>
      <webElementGuid>941029b3-5a8c-4d34-99fd-fa729563d4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f3dec0cf-fb2c-418d-a180-ef3f97d585cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.isInValid  || AddEditUserCtrl.customFieldForm.$invalid  || AddEditUserCtrl.userForm.$invalid || AddEditUserCtrl.customFieldFormAdd.$invalid</value>
      <webElementGuid>810d2c1e-c0ff-490a-a252-63aee2204325</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-click</name>
      <type>Main</type>
      <value>AddEditUserCtrl.saveUser()</value>
      <webElementGuid>b5ea09eb-4baf-49d3-b854-c09db856d87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'text-muted':!AddEditUserCtrl.isInEditMode,'lms-color-lnks':AddEditUserCtrl.isInEditMode,'lms-disabled': AddEditUserCtrl.isInValid  || AddEditUserCtrl.customFieldForm.$invalid  || AddEditUserCtrl.userForm.$invalid || AddEditUserCtrl.customFieldFormAdd.$invalid}</value>
      <webElementGuid>4ac8c878-5e4a-4b75-bfa4-5d47e8383652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                                     Save
                                </value>
      <webElementGuid>68c37cf9-7191-41ac-9fd2-7fff053d524a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnClosePopup&quot;)</value>
      <webElementGuid>bca130ff-de72-4f42-b122-190aaa2a5050</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnClosePopup']</value>
      <webElementGuid>eaa3669d-28c9-4c9a-8faf-e2d24b3d4fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/footer/div/button</value>
      <webElementGuid>667568ca-b2cb-4d0e-bbf6-1c67c2fb845a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Initiate Calendar'])[3]/following::button[1]</value>
      <webElementGuid>a7d55f6b-6281-4ed7-bfc8-aa2a13a30a8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>cee20ee0-6f4c-4e07-ac59-0159a146e7bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>3f2c264f-e5e5-47c8-8619-c148d55e294d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//footer/div/button</value>
      <webElementGuid>377d595e-be4c-4e40-9626-641912e026de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnClosePopup' and @type = 'button' and (text() = '
                                     Save
                                ' or . = '
                                     Save
                                ')]</value>
      <webElementGuid>a5330f4b-7b10-4546-8def-215bcebe50ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
