<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Text_TextArea</name>
   <tag></tag>
   <elementGuidId>9dbb6fcb-34e3-45ff-b931-4ad1a68f8b0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='txtCustomField1']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtCustomField1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>6ff1b053-58bd-4c9c-a32f-4561c5aa890f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6176d904-2dee-4e8b-8a19-4e7d7d392f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtCustomField1</value>
      <webElementGuid>4490fb39-3009-4f21-91bb-366b58c3c446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>txtCustomField1</value>
      <webElementGuid>4ef3db34-7eb2-4018-af93-b6b56fc9c9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-required</name>
      <type>Main</type>
      <value>customField.IsRequired</value>
      <webElementGuid>fffbc5c5-eab5-4cda-ac82-d6586cb548d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lms-border lms-full-width lms-border-radius-10 lms-padding-10 lms-outline-0 lms-textarea-fixed-width ng-untouched ng-valid ng-valid-required ng-valid-pattern ng-valid-minlength ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>168f2220-4170-44ad-bc47-10a8ce5f1d19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'lms-disabled':customFieldListCtrl.disabled , 'border-error': ( customFieldListCtrl.customFieldForm.txtCustomField1.$invalid &amp;&amp; !customFieldListCtrl.customFieldForm.txtCustomField1.$pristine)
                            || (customFieldListCtrl.customFieldForm.txtCustomField1.$invalid &amp;&amp; submitted ) ,

                          'success': customFieldListCtrl.customFieldForm.txtCustomField1.$valid
                          &amp;&amp; customFieldListCtrl.customFieldForm.txtCustomField1.$touched &amp;&amp; !customFieldListCtrl.customFieldForm.txtCustomField1.$pristine }</value>
      <webElementGuid>2ac46aa9-b55a-46ae-869c-9957c457adc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>7468747e-280c-41a8-887e-8e32f5d688bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>customField.Value</value>
      <webElementGuid>8d22dcf1-2113-47d7-a8b4-5d4c3561aa7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>207391e3-e33b-4e21-ac51-846438d018e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6421c58a-1b3d-42f8-884a-b918f7b271b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c5a815ca-868b-4178-a384-57f2a7e3dc15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>02ddd323-2475-499b-bf37-d7c5250a7148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-wsc-instance</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>875f6d05-d26e-45b1-9699-953b44960e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtCustomField1&quot;)</value>
      <webElementGuid>07061662-5856-4e0e-871d-62256fd5f2c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='txtCustomField1']</value>
      <webElementGuid>22172d5a-e1b9-4715-bc15-422c3d455893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div[3]/div/div/div/div/div/custom-field-list/div/div/ng-form/div[2]/div/textarea</value>
      <webElementGuid>b0c336be-6588-46a4-98ab-2477951203a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>64318f77-9e3f-4d88-9ea8-9378d7a8e170</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@type = 'text' and @id = 'txtCustomField1' and @name = 'txtCustomField1']</value>
      <webElementGuid>f3d5686c-7063-45f2-aa38-66230b781f3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
