<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Confirm Password_TextField</name>
   <tag></tag>
   <elementGuidId>e03baa8e-04ae-478f-8478-cda5ea436efd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='resetPassword']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;resetPassword&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>35f60b07-e597-4b2f-a9a2-72d8ecb98675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required</value>
      <webElementGuid>a84339ed-715b-4edc-a6ae-f92b17d4c3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>resetPassword</value>
      <webElementGuid>88593357-ae13-49d9-b51b-7fa01cbd8507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.resetPasswordBusy</value>
      <webElementGuid>da4fda77-4871-4721-85c9-e81951b857c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.confirmPassword</value>
      <webElementGuid>e066875d-3a01-4054-a5c3-88e2697682ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value> Retype Password</value>
      <webElementGuid>51de9ad8-4559-4c95-92a8-4eeacde11a07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>2812fd88-4e03-46f7-9501-db38db661e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5f9035d7-8a29-48f9-abd2-6176546bf15c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error': AddEditUserCtrl.userForm.resetPassword.$invalid &amp;&amp; AddEditUserCtrl.userForm.resetPassword.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.resetPassword.$pristine || submitted),'lms-border-error': AddEditUserCtrl.user.confirmPassword &amp;&amp; (AddEditUserCtrl.user.confirmPassword !=AddEditUserCtrl.user.password)}</value>
      <webElementGuid>5c9a99bc-033c-4375-9b68-0cd52193b83c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c73b1caf-01fc-485c-a5fb-9b35c184e7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;divPasswordSetting&quot;)/div[@class=&quot;row lms-margin-0&quot;]/div[@class=&quot;col-xs-12 lms-padding-top-2 lms-text-align-start lms-xs-only-padding-end-0-imp&quot;]/div[@class=&quot;col-sm-5 lms-xs-only-margin-top-20&quot;]/input[@class=&quot;form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required&quot;]</value>
      <webElementGuid>84fbf2fb-8992-4b17-b2b8-393e0cc99198</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='resetPassword']</value>
      <webElementGuid>3f872f2f-79e4-4838-bad1-2edb61003c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divPasswordSetting']/div/div[3]/div[2]/input</value>
      <webElementGuid>197f33b3-df76-404b-9d74-75b377c22c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>5df20f19-1648-4e49-9332-51fdb0275e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'resetPassword' and @placeholder = ' Retype Password' and @type = 'password']</value>
      <webElementGuid>b7e5f6bf-938f-4b8d-a1ab-61e2637674b6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
