<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>User Email_TextField</name>
   <tag></tag>
   <elementGuidId>6484c6a2-1e66-499b-8077-221f2c780299</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='txtEmail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#txtEmail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>90f3c736-3be7-4597-b3a0-bc4b3f627a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2184dade-56fd-4cf1-b5ac-00c4be9eea7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>txtEmail</value>
      <webElementGuid>b0709159-def1-4127-869a-40a4301058ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-minlength ng-valid-maxlength</value>
      <webElementGuid>b925e9a0-49e0-46bf-8895-136b10bd515a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>name@example.com</value>
      <webElementGuid>be9d40b1-b567-469a-9398-5ae22545b0d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>5f1a44dd-b4f8-44e7-a640-d9fc96170502</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>07f794fb-c4a1-48b2-a173-c62ea72fe1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>AddEditUserCtrl.user.Email</value>
      <webElementGuid>8db098b8-3c0c-4d48-ab63-a32e93a57333</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>be806391-e0b4-4f1a-9150-7746cb14334d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-minlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aff321cd-7bc1-4e92-9cd9-5edf7fa27fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-maxlength</name>
      <type>Main</type>
      <value>254</value>
      <webElementGuid>d87af36c-28e1-4fe6-9eb5-06ffb2a3a49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-disabled</name>
      <type>Main</type>
      <value>AddEditUserCtrl.isInEditMode</value>
      <webElementGuid>a22b3626-ae83-4591-9c29-62bb56499188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-blur</name>
      <type>Main</type>
      <value>AddEditUserCtrl.emailPattern()</value>
      <webElementGuid>f61d21ea-b6b4-410c-9ce7-6a52e0848155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ng-class</name>
      <type>Main</type>
      <value>{'border-error':AddEditUserCtrl.userForm.Email.$invalid &amp;&amp; AddEditUserCtrl.userForm.Email.$error.required  &amp;&amp; (!AddEditUserCtrl.userForm.Email.$pristine || submitted), 'lms-border-error': AddEditUserCtrl.hidePatternMessage === false}</value>
      <webElementGuid>99612fd3-870d-4516-8437-67cd5903da87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>da5e7ddd-651c-4e73-b88b-d8412001a811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;txtEmail&quot;)</value>
      <webElementGuid>afca40ee-a472-43e7-9884-2843404e81a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='txtEmail']</value>
      <webElementGuid>42bbf666-d3f2-4cc9-a42b-402cca83ed62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divAddEditUser']/div/div/form/div/fieldset/div/div/div/div/div/div[2]/div[2]/div[2]/div/input</value>
      <webElementGuid>282186dd-9b4a-4db3-88e7-952287b6eaf6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>a671ef64-af8e-415c-a270-7f2376d0cfb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'txtEmail' and @placeholder = 'name@example.com' and @title = 'Email' and @name = 'Email']</value>
      <webElementGuid>5e21d576-2985-41de-99b6-b69e0e3eef48</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
